package: 123

config:
  - branch: 'main'
    release: 'c9s'
  - branch: 'rhel-9.0.0'
    release: '9.0.0'
  - branch: 'rhel-9.1.0'
    release: '9.1.0'

rules:
  someRandomStuff:

  bugzillaReference:
    label: 'needs-bz'

  jiraReference: 'SomeRandomValue'

  review:
    label: 10

  ci:
    label: 'needs-ci'

  upstreamReference:
    label: 'needs-upstream'

  flags:
    label: 'needs-flags'
    flags: ['qa_ack', 'devel_ack', 'release']
  