# Repository specification
package: systemd
mainBranch: 'main'
branchPrefix: 'rhel-'
rhel: [9.0.0-beta, 9.0.0, 9.1.0, ...]
# TODO: come up with configuration (branch name x rhel version x main/master)

# Pull-request rules
rules:
  bugzillaReference:
    label: 'needs-bz'

  review: 
    label: 'needs-review'

  ci:
    label: 'needs-ci'

  upstreamReference: 
    label: 'needs-upstream'

  flags:
    label: 'needs-flags'
    flags: ['qa_ack', 'devel_ack', 'release']
