name: Linting suite

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint:
    name: Linters
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn

      - name: Install Node.js dependencies
        run: yarn install

      - name: Run Prettier
        run: yarn run lint:prettier

      # - name: Run CSpell
      #   run: yarn run lint:spellcheck      
